# Generated by Django 5.2.6 on 2025-09-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0002_customuser_age_customuser_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('mobile', models.CharField(max_length=15)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
