# Generated by Django 5.2.6 on 2025-09-23 06:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0003_otptable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='from_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='from_state',
            new_name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='to_city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='to_state',
        ),
        migrations.AddField(
            model_name='customuser',
            name='adhaar_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 23, 6, 53, 1, 473319, tzinfo=datetime.timezone.utc)),
        ),
    ]
