# Generated by Django 5.2.6 on 2025-09-26 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0005_service_alter_otptable_expired_at_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 26, 6, 26, 47, 791328, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
