# Generated by Django 5.2.6 on 2025-10-10 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0007_service_alter_otptable_expired_at_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('contact_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rooms', models.IntegerField(default=0)),
                ('available_rooms', models.IntegerField(default=0)),
                ('hostel_type', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10)),
                ('meal_include', models.BooleanField(default=False)),
                ('curfew_time', models.TimeField(blank=True, null=True)),
                ('warden_name', models.CharField(blank=True, max_length=100, null=True)),
                ('average_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('nearby', models.TextField(blank=True, null=True)),
                ('common_offer', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(choices=[('Luxury', 'Luxury'), ('Standard', 'Standard')], default='Standard', max_length=20)),
                ('events', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_views', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 7, 17, 13, 760140, tzinfo=datetime.timezone.utc)),
        ),
    ]
