# Generated by Django 5.2.6 on 2025-10-10 07:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0008_hostel_alter_otptable_expired_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 7, 40, 25, 773486, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Triple', 'Triple')], max_length=20)),
                ('floor_no', models.IntegerField()),
                ('ac_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=10)),
                ('furnished_status', models.CharField(choices=[('Furnished', 'Furnished'), ('Semi-Furnished', 'Semi-Furnished'), ('Unfurnished', 'Unfurnished')], max_length=20)),
                ('bed_type', models.CharField(choices=[('Single Bed', 'Single Bed'), ('Bunk Bed', 'Bunk Bed'), ('Double Bed', 'Double Bed')], max_length=20)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(default=1)),
                ('old_user_counts', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='StudIQApi.hostel')),
            ],
        ),
    ]
