# Generated by Django 5.2.6 on 2025-10-10 07:58

import cloudinary.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0009_alter_otptable_expired_at_hostelroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 10, 8, 3, 29, 412439, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='HostelFacility',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('warden', models.BooleanField(default=False)),
                ('visitors', models.BooleanField(default=False)),
                ('tv_lounge', models.BooleanField(default=False)),
                ('gym_access', models.BooleanField(default=False)),
                ('ro_water', models.BooleanField(default=False)),
                ('fire_safety', models.BooleanField(default=False)),
                ('washing_machine', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('geyser', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('open_terrace', models.BooleanField(default=False)),
                ('hostel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='StudIQApi.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='HostelPhoto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', cloudinary.models.CloudinaryField(max_length=255)),
                ('is_banner', models.BooleanField(default=False)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='StudIQApi.hostel')),
            ],
        ),
    ]
