# Generated by Django 5.2.6 on 2025-10-13 11:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudIQApi', '0012_alter_customuser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='StudIQApi.customuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otptable',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 13, 11, 41, 1, 322776, tzinfo=datetime.timezone.utc)),
        ),
    ]
